import React, { useEffect, useRef, useState } from 'react';
import { Files, MagnifyingGlass, GitBranch, Play, DownloadSimple, Copy, Check, ArrowLeft, ArrowSquareOut, Desktop, List, X, FolderOpen, Table, TextAlignRight, CheckCircle, BookOpen, WarningCircle } from '@phosphor-icons/react';
import { stages, platforms, resources, categories } from './content';
import DatasetLibrary from './DatasetLibrary';
import Exercise from './Exercise';
import ExerciseMap from './ExerciseMap';
import AgentBuilder from './AgentBuilder';
const icons = {files:Files, search:MagnifyingGlass, branches:GitBranch, video:Play, table:Table, text:TextAlignRight, check:CheckCircle, desktop:Desktop};
const asset = (path) => typeof __OFFLINE_ASSETS__ !== "undefined" && __OFFLINE_ASSETS__[path] ? __OFFLINE_ASSETS__[path] : `${import.meta.env.BASE_URL}${path}`;
const researchAlt={collection:'מיון חומרי מחקר לתיקיות',evidence:'השוואה בין מקורות ובחינת ראיות',argument:'דיון משותף בפרשנויות למחקר'};
function ResearchPhoto({kind,className=''}){return <img className={`research-photo ${className}`} src={asset(`assets/research-${kind}.jpg`)} alt={`המחשה שנוצרה באמצעות AI: ${researchAlt[kind]}`} width="1400" height="933"/>;}
function Icon({name, size=26, ...props}) { const I = icons[name] || Files; return <I size={size} weight="light" aria-hidden="true" {...props}/>; }
function go(path) { window.location.hash = path; }
function Button({children, secondary=false, ...props}) { return <button className={`button ${secondary?'secondary':''}`} {...props}>{children}</button>; }
function Status({pending=false}) { return <span className={`status ${pending?'pending':''}`}>{pending?'בהכנה':'זמין'}</span>; }
function PlatformSelect({value,onChange}) {return <label className="platform-select"><span>סביבת העבודה</span><select value={value} onChange={e=>onChange(e.target.value)} aria-label="סביבת העבודה">{platforms.map(p=><option value={p.id} key={p.id}>{p.name}{p.id==='chatgpt'?' · ברירת מחדל':''}</option>)}</select></label>;}
function StageRoute({compact=false}) {return <div className={`stage-route ${compact?'compact':''}`}>{stages.map((s,i)=><React.Fragment key={s.id}><a href={`#stage/${s.id}`} className="route-step"><span className="number">{s.number}</span><span className="icon-disc"><Icon name={s.icon} size={34}/></span><div><h3>{s.title}</h3><p>{s.short}</p>{!compact&&<span className="checkpoint-mini"><CheckCircle size={17}/> בדיקת החוקר</span>}</div></a>{compact&&i<2&&<ArrowLeft aria-hidden="true" size={24}/>}</React.Fragment>)}</div>;}
function ResourceAction({r}) {if(r.action==='dataset')return <a className="text-action" href="#resources/data">בחירת קבצים <ArrowLeft size={18}/></a>;if(r.status==='pending')return <Status pending/>;if(r.href)return <a className="text-action" href={asset(r.href)} download={r.href.split("/").pop()}><DownloadSimple size={19}/> הורדה</a>;return <a className="text-action" href={r.action==='platform'?`#tools/${r.platform}`:`#stage/${r.stageId}/${r.action==='video'?'video':'diagram'}`}>פתיחה <ArrowLeft size={18}/></a>;}
function ResourceRow({r}) {return <article className="resource-row"><span className="icon-disc"><Icon name={r.icon}/></span><div className="resource-main"><h3 dir="auto">{r.title}</h3><p>{r.description}</p><div className="resource-meta">{r.category} <span>·</span> {r.stage}</div></div><ResourceAction r={r}/></article>;}
function Landing() {
 return <div className="landing-page"><section className="forum-hero">
 <h1 className="forum-title" aria-label="פל״א - פורום למחקר איכותני"><span className="forum-display">פל״א</span><span className="sr-only"> - פורום למחקר איכותני</span></h1>
 {[1,2,3].map((slice)=><figure key={slice} className={`forum-image forum-slice-${slice}`} aria-hidden={slice!==1}><img src={asset('assets/qualitative-interview.jpg')} alt={slice===1?'תמונת המחשה שנוצרה באמצעות AI: שיחה, כתיבה במחברת ומכשיר הקלטה על השולחן':''} width="1536" height="1024" fetchPriority="high"/><span className="forum-photo-title forum-display" aria-hidden="true">פל״א</span></figure>)}
 <div className="forum-copy"><p className="eyebrow">מפגש עמיתים ושיח במחקר איכותני</p><p className="forum-name">הפורום למחקר איכותני</p><div className="forum-description"><h2>בוחנים יחד את העבודה<br/>עם סוכני AI במחקר איכותני</h2></div><a className="button" href="#workshop">כניסה למרחב הסדנה <ArrowLeft size={23}/></a><p className="forum-date">17 בספטמבר 2026 <span>/</span> בהנחיית יניב פוקס</p></div>
 </section><nav className="landing-shortcuts" aria-label="גישה ישירה למשאבי הסדנה"><a href="#workshop"><span className="eyebrow">01 / התהליך</span><span>התרגיל שלנו <ArrowLeft size={20}/></span></a><a href="#build"><span className="eyebrow">02 / הסוכן</span><span>בונים סוכן <ArrowLeft size={20}/></span></a><a href="#map"><span className="eyebrow">03 / במבט אחד</span><span>מפת התרגיל <ArrowLeft size={20}/></span></a></nav></div>;
}
function Home() {return <>
 <section className="home-intro"><div className="hero-copy"><p className="eyebrow">מרחב העבודה של הסדנה</p><h1>בינה איכותנית</h1><h2>עבודה עם סוכני AI<br className="desktop-break"/> במחקר איכותני</h2><p className="hero-description">מרחב ללמידה משותפת, לשיתוף בניסיון ולדיון בשאלות מתודולוגיות. בסדנה נבחן כיצד לעבוד עם סוכני AI : מהכנת חומרי המחקר ועד לבחינת פרשנויות וטענות.</p><Button onClick={()=>go('tools/chatgpt')}>מתחילים כאן <ArrowLeft size={24}/></Button><p className="event-line">17 בספטמבר 2026 <span> / </span> סדנת בינה איכותנית <span> / </span> יניב פוקס</p></div><StageRoute/></section>
 <ResearchPhoto kind="argument" className="overview-photo"/><section className="home-resources"><div className="section-intro"><span className="section-icon"><FolderOpen size={38} weight="light"/></span><h2>חומרי התרגול</h2><p>קבצים, תבניות והנחיות שילוו את העבודה. לצד כל פריט מצוין אם הוא כבר זמין.</p><a className="text-action" href="#resources">לכל המשאבים <ArrowLeft size={19}/></a></div><div className="home-resource-list">{[resources[0],resources.find(r=>r.id==='evidence-template'),resources.find(r=>r.id==='prompts')].map(r=><ResourceRow r={r} key={r.id}/>)}</div></section>
 <section className="platform-strip"><div><Desktop size={27} weight="light"/><div><span className="eyebrow">סביבת העבודה הראשית</span><a href="#tools/chatgpt"><bdi>ChatGPT Desktop</bdi><span className="small"> · ברירת מחדל</span></a></div></div><div className="other-platforms"><span>משתמשים בכלי אחר?</span><div>{platforms.slice(1).map(p=><a href={`#tools/${p.id}`} key={p.id}><bdi>{p.name}</bdi></a>)}</div></div></section>
 </>;}
function Sidebar({active}) {return <aside className="stage-sidebar"><details className="disclosure route-disclosure"><summary>מסלול הסדנה <span className="disclosure-context">{stages.find(s=>s.id===active)?.title}</span></summary><nav aria-label="מסלול הסדנה"><a className="sidebar-link" href="#tools/chatgpt"><span className="number">00</span><h3>הכנה והתקנה</h3></a>{stages.map(s=><a key={s.id} href={`#stage/${s.id}`} className={`sidebar-link ${active===s.id?'selected':''}`} aria-current={active===s.id?'step':undefined}><span className="number">{s.number}</span><h3>{s.title}</h3></a>)}<a className="sidebar-library" href="#resources"><BookOpen size={25}/><span>ספריית משאבים</span></a></nav></details></aside>;}

let diagramCounter=0;
function Diagram({stage}) {
 const host=useRef(null); const [error,setError]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let alive=true;setReady(false);setError(false);const id=`diagram-${++diagramCounter}`;const code=`flowchart RL\n A["${stage.diagram[0]}"] --> B["${stage.diagram[1]}"]\n B --> C{"${stage.diagram[2]}"}\n C -->|"מאושר"| D["${stage.diagram[3]}"]\n C -->|"נדרש תיקון"| B`;
 (async()=>{try{const {default:mermaid}=await import('mermaid');await document.fonts.load('18px Assistant');await document.fonts.ready;if(!alive)return;mermaid.initialize({startOnLoad:false,htmlLabels:false,securityLevel:'strict',theme:'base',themeVariables:{fontFamily:'Assistant, sans-serif',fontSize:'18px',primaryColor:'#ebe9dc',primaryTextColor:'#004128',primaryBorderColor:'#6b7a5e',lineColor:'#8b7029',secondaryColor:'#eee5ca',tertiaryColor:'#f6f4ec'},flowchart:{htmlLabels:false,curve:'linear',padding:22}});const {svg}=await mermaid.render(id,code);if(alive&&host.current){host.current.innerHTML=svg;setReady(true);}}catch{if(alive)setError(true);}})();return()=>{alive=false;};},[stage]);
 function download(){const svg=host.current?.querySelector('svg');if(!svg)return;const blob=new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${stage.id}-workflow.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="diagram-block"><div className="panel-heading"><div><span className="eyebrow">התהליך במבט אחד</span><h3>{stage.videoTitle}</h3></div><button className="text-action" onClick={download} disabled={!ready}><DownloadSimple size={19}/> הורדת התרשים</button></div><div className="diagram" ref={host} role="img" aria-label={`תרשים: ${stage.diagram.join(', ')}. אם נדרש תיקון, חוזרים לשלב הקודם.`}>{error?<p>התרשים לא נטען. אפשר לעקוב אחר רצף העבודה המופיע מתחת.</p>:<p>טוען את התרשים…</p>}</div><ol className="diagram-text">{stage.diagram.map(t=><li key={t}>{t}</li>)}</ol><p className="muted">אם הבדיקה מעלה פערים, חוזרים לדוגמה ומתקנים לפני שמרחיבים את העבודה.</p></section>;
}
function CopyPrompt({stage}) {const [copied,setCopied]=useState(false);const [failed,setFailed]=useState(false);useEffect(()=>{setCopied(false);setFailed(false)},[stage]);async function copy(){try{await navigator.clipboard.writeText(stage.prompt);setCopied(true);setFailed(false);setTimeout(()=>setCopied(false),2500);}catch{setFailed(true);}}return <section className="prompt-block"><div className="panel-heading"><div><span className="eyebrow">נוסח התחלתי להתאמה</span><h3>הנחיה לסוכן</h3></div><Button secondary onClick={copy}>{copied?<Check size={19}/>:<Copy size={19}/>} {copied?'הועתק':'העתקת ההנחיה'}</Button></div><details className="disclosure prompt-disclosure" open={failed?true:undefined}><summary>קריאה והתאמה של ההנחיה</summary><p className="muted">במסלול הקצר ממשיכים באותה משימה ובאותה מחברת. אפשר להתאים את ההנחיה לשאלה אחרת.</p><pre className="prompt-text" tabIndex="0">{stage.prompt}</pre></details><p className="copy-status" role="status">{failed?'ההעתקה האוטומטית לא זמינה. סמנו את הטקסט והעתיקו ידנית.':copied?'ההנחיה הועתקה. אפשר להדביק אותה בסביבת העבודה.':''}</p></section>;}
const videoFiles = {collection:'01-prepare',evidence:'02-evidence',argument:'03-interpretation'};
function VideoPlan({stage,full=false}) {
 const file=videoFiles[stage.id];
 return <section className={`video-plan ${full?'full':''}`}>
 <div className="video-player"><video key={stage.id} controls playsInline preload="metadata" poster={asset(`videos/${file}.jpg`)} aria-label={stage.videoTitle}><source src={asset(`videos/${file}.mp4`)} type="video/mp4"/>הדפדפן אינו תומך בניגון הסרטון. אפשר להוריד אותו מהקישור שמתחת.</video><div className="video-caption"><span>דקה אחת · טקסט, אנימציה ומוזיקה</span><a className="text-action" href={asset(`videos/${file}.mp4`)} download={`${file}.mp4`}><DownloadSimple size={18}/> הורדת הסרטון</a></div></div>
 {full&&<div className="video-outline"><h3>{stage.videoTitle}</h3><ol>{stage.beats.map(b=><li key={b}>{b}</li>)}</ol><p className="muted">כל ההסברים מופיעים על המסך. אפשר לצפות גם ללא צליל.</p><a className="text-action" href={`#stage/${stage.id}/instructions`}>להנחיות העבודה <ArrowLeft size={18}/></a></div>}
 </section>;
}
function Stage({id,tab='overview',platform,setPlatform}) {const stage=stages.find(s=>s.id===id);if(!stage)return <NotFound/>;const p=platforms.find(p=>p.id===platform);const tabs=[['overview','השלב בקצרה'],['instructions','הנחיות העבודה'],['diagram','תרשים התהליך'],['video','הדגמה חזותית']];return <div className="stage-layout"><p className="extension-notice">חומר הרחבה מהמסלול המפורט. אינו צעד נדרש בתרגיל. <a href="#workshop">חזרה לתרגיל שלנו ←</a></p><Sidebar active={id}/><div className="stage-content"><details className="disclosure platform-disclosure"><summary>סביבת העבודה <bdi>{p.name}</bdi></summary><PlatformSelect value={platform} onChange={setPlatform}/></details><header className={`stage-heading ${tab==='overview'?'visual-heading':'text-heading'}`}><div><p className="eyebrow">שלב {stage.number}</p><h1>{stage.title}</h1><p className="subtitle">{stage.subtitle}</p></div>{tab==='overview'&&<ResearchPhoto kind={id}/>}</header><nav className="page-tabs" aria-label="תוכן השלב">{tabs.map(([key,label])=><a key={key} className={tab===key?'active':''} href={`#stage/${id}/${key}`} aria-current={tab===key?'page':undefined}>{label}</a>)}</nav>
 {tab==='overview'&&<><div className="stage-overview"><ol className="instruction-list">{stage.steps.map(([title,text],i)=><li key={title}><details className="disclosure step-disclosure"><summary><span className="number">0{i+1}</span><span>{title}</span></summary><p>{text}</p></details></li>)}</ol><div><details className="disclosure video-disclosure"><summary>צפייה בהדגמה החזותית</summary><VideoPlan stage={stage}/></details><a className="stage-files" href="#resources/data"><FolderOpen size={29} weight="light"/><div><strong>קובצי התרגול</strong><p>קובץ אחד עם שלושה ראיונות בעמוד התרגיל</p></div><ArrowLeft size={20}/></a></div></div><div className="checkpoint"><WarningCircle size={32} weight="light"/><div><h3>עוצרים ובודקים</h3><p>{stage.checkpoint}</p></div><Button onClick={()=>go(`stage/${id}/instructions`)}>להנחיות העבודה <ArrowLeft size={21}/></Button></div><div className="expected-output"><span className="eyebrow">עם מה יוצאים מהשלב?</span><p>{stage.goal}</p></div></>}
 {tab==='instructions'&&<><div className="platform-note"><Desktop size={25}/><div><strong><bdi>{p.name}</bdi></strong><p>{p.stageNote}</p><a href={`#tools/${p.id}`}>למדריך ההתקנה</a></div></div><CopyPrompt stage={stage}/><section className="checklist-section"><h3>לפני שממשיכים</h3>{['מצאתי את התוצרים ובדקתי אותם מול המקור.','תיעדתי מה לא ברור ומה דורש בדיקה נוספת.','החלטתי אם לתקן, להרחיב או לעצור.'].map(t=><label key={`${id}-${t}`}><input type="checkbox"/>{t}</label>)}</section><div className="next-stage"><p>אפשר לחזור לכל שלב גם בהמשך.</p><Button onClick={()=>go(stage.number==='03'?'resources':`stage/${stages[Number(stage.number)].id}`)}>{stage.number==='03'?'לספריית המשאבים':'לשלב הבא'}<ArrowLeft size={22}/></Button></div></>}
 {tab==='diagram'&&<Diagram stage={stage}/>}{tab==='video'&&<VideoPlan stage={stage} full/>}{!tabs.some(([key])=>key===tab)&&<NotFound/>}
 </div></div>;}
function Library({initialCategory}) {const [query,setQuery]=useState('');const [category,setCategory]=useState(initialCategory==='data'?'נתונים':'הכול');const [stage,setStage]=useState('הכול');useEffect(()=>setCategory(initialCategory==='data'?'נתונים':'הכול'),[initialCategory]);const found=resources.filter(r=>(category==='הכול'||r.category===category)&&(stage==='הכול'||r.stage===stage||r.stage==='כל השלבים')&&`${r.title} ${r.description} ${r.category} ${r.stage}`.toLowerCase().includes(query.trim().toLowerCase()));return <><header className="library-heading visual-heading"><div><p className="eyebrow">חומרי הרחבה</p><h1>האוסף המלא<br/>לעיון ולהמשך.</h1><p className="subtitle">בסדנה עצמה עובדים עם קובץ אחד. <a href="#workshop">לתרגיל שלנו ←</a></p></div><ResearchPhoto kind="collection"/></header><DatasetLibrary asset={asset}/><div className="library-layout"><aside className="library-setup"><details className="disclosure"><summary>הכנה והתקנה</summary><p>בוחרים כלי אחד ומכינים את סביבת העבודה.</p><div className="default-platform"><Desktop size={35} weight="light"/><h3><bdi>ChatGPT Desktop</bdi></h3><span>ברירת המחדל בסדנה</span><Button onClick={()=>go('tools/chatgpt')}>למדריך ההתקנה <ArrowLeft size={20}/></Button></div><p className="small">מסלולים נוספים</p>{platforms.slice(1).map(p=><a className="platform-link" key={p.id} href={`#tools/${p.id}`}><bdi>{p.name}</bdi><ArrowLeft size={18}/></a>)}</details></aside><section className="resource-browser"><label className="search-box"><MagnifyingGlass size={28} weight="light"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="מה תרצו למצוא?" aria-label="חיפוש משאבים"/>{query&&<button aria-label="ניקוי החיפוש" onClick={()=>setQuery('')}><X size={19}/></button>}</label><div className="filter-tabs" role="group" aria-label="סוג משאב">{categories.map(c=><button key={c} className={c===category?'active':''} aria-pressed={c===category} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="results-heading"><span role="status">{found.length} פריטים מוצגים</span><label>שלב <select value={stage} onChange={e=>setStage(e.target.value)} aria-label="סינון לפי שלב"><option>הכול</option><option>הכנה והתקנה</option>{stages.map(s=><option key={s.id}>{s.title}</option>)}</select></label></div>{found.length?found.map(r=><ResourceRow key={r.id} r={r}/>):<div className="empty-state"><MagnifyingGlass size={36} weight="light"/><h3>לא נמצאו משאבים מתאימים</h3><p>נסו מילת חיפוש אחרת או הרחיבו את הסינון.</p><Button secondary onClick={()=>{setQuery('');setCategory('הכול');setStage('הכול')}}>ניקוי הסינון</Button></div>}</section></div><StageRoute compact/></>;}
function Tools({selected,setPlatform}) {const p=platforms.find(p=>p.id===selected)||platforms[0];return <><header className="tools-heading visual-heading"><div><p className="eyebrow">שלב 00 / הכנה והתקנה</p><h1>מכינים את סביבת העבודה.</h1><p className="subtitle">כלי אחד, תיקיית תרגול אחת, ומשימה ברורה.</p></div><ResearchPhoto kind="collection"/></header><div className="tools-layout"><details className="disclosure tool-menu"><summary>בחירת כלי <bdi>{p.name}</bdi></summary><nav className="tool-nav" aria-label="בחירת כלי">{platforms.map(tool=><a className={tool.id===p.id?'selected':''} href={`#tools/${tool.id}`} key={tool.id}><Desktop size={25} weight="light"/><span><bdi>{tool.name}</bdi><small>{tool.label}</small></span></a>)}</nav></details><section className="tool-detail"><div className="tool-detail-heading"><div><span className="eyebrow">{p.label}</span><h2><bdi>{p.name}</bdi></h2></div><a href={p.url} className="button" target="_blank" rel="noreferrer">{p.linkLabel}<ArrowSquareOut size={21}/></a></div><p className="tool-intro">{p.intro}</p><details className="disclosure setup-disclosure" key={p.id}><summary>שלבי ההתקנה וההתחלה</summary><ol className="setup-steps">{p.steps.map((text,i)=><li key={text}><span className="number">0{i+1}</span><p>{text}</p></li>)}</ol></details><details className="disclosure tool-note"><summary>כדאי לדעת</summary><p>{p.note}</p></details><p className="source-note">קישור ומידע נבדקו ב־16.09.2026 · <a href={p.source} target="_blank" rel="noreferrer">{p.sourceLabel}<ArrowSquareOut size={14}/></a></p><div className="tool-next"><Button onClick={()=>{setPlatform(p.id);go('stage/collection')}}>ממשיכים עם <bdi>{p.name}</bdi><ArrowLeft size={20}/></Button></div></section></div><section className="help-section"><h2>אם משהו לא עובד</h2><details><summary>אין לי אפשרות לעבוד עם סוכן בחשבון</summary><p>בדקו שנכנסתם לחשבון המתאים באפליקציית שולחן העבודה ושמצב העבודה הסוכני זמין בו. אם אין גישה, פנו למנחה לבחירת אחת מסביבות העבודה הסוכניות של הסדנה.</p></details><details><summary>הסוכן לא מצליח לקרוא את הקובץ</summary><p>בקשו רשימה של הקבצים שנקראו ושל אלה שלא נקראו. נסו תחילה קובץ טקסט קצר. אל תמשיכו לניתוח אם הסוכן לא יכול להציג קטע מדויק מן החומר שסיפקתם.</p></details><details><summary>איפה מוצאים את חומרי התרגול?</summary><p>קובץ התרגיל זמין להורדה בעמוד התרגיל, בצעד הראשון. <a href="#workshop">לעמוד התרגיל</a></p></details></section></>;}
function NotFound(){return <section className="empty-state"><h1>העמוד לא נמצא</h1><p>הדף הזה כבר אינו חלק מהסדנה. התרגיל, בונים סוכן ומפת התרגיל נמצאים בתפריט למעלה.</p><a className="button" href="#home">לעמוד הראשי <ArrowLeft size={20}/></a></section>;}
export function App(){const [hash,setHash]=useState(window.location.hash.slice(1)||'home');const [platform,setPlatform]=useState('chatgpt');const [menu,setMenu]=useState(false);const main=useRef(null);
 const [transition,setTransition]=useState('idle');
 useEffect(()=>{
   let timer;
   const fn=()=>{
     const next=window.location.hash.slice(1)||'home';
     clearTimeout(timer);
     setMenu(false);
     if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){
       setHash(next);setTransition('idle');return;
     }
     setTransition('leaving');
     timer=setTimeout(()=>{setHash(next);setTransition('entering');},140);
   };
   window.addEventListener('hashchange',fn);
   return()=>{clearTimeout(timer);window.removeEventListener('hashchange',fn);};
 },[]);useEffect(()=>{const [page,id]=hash.split('/');const title=page==='map'?'מפת התרגיל':page==='build'?'בונים סוכן':page==='home'?'פל״א - פורום למחקר איכותני':'מרחב העבודה';document.title=`${title||'בינה איכותנית'} | HIGH AI`;window.scrollTo(0,0);main.current?.focus({preventScroll:true});},[hash]);const [page,id,tab]=hash.split('/');const nav=[['home','פל״א'],['workshop','התרגיל שלנו'],['build','בונים סוכן'],['map','מפת התרגיל']];return <><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();main.current?.focus()}}>דילוג לתוכן</a><div className="site-shell"><header className="site-header"><a className="brand" href="#home" aria-label="HIGH AI : לעמוד הראשי"><img src={asset('assets/high-ai-logo.jpg')} width="220" height="88" alt="HIGH AI : AI for Outstanding Research, Bar-Ilan University"/></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'סגירת תפריט':'פתיחת תפריט'}>{menu?<X size={27}/>:<List size={27}/>}</button><nav className={menu?'open':''} aria-label="ניווט ראשי">{nav.map(([href,title])=><a href={`#${href}`} key={href} className={page===href.split('/')[0]?'active':''} aria-current={page===href.split('/')[0]?'page':undefined}>{title}</a>)}</nav></header><main id="main-content" ref={main} tabIndex="-1" className={`page-transition ${transition}`}>{page==='home'?<Landing/>:page==='workshop'?<Exercise asset={asset}/>:page==='map'?<ExerciseMap/>:page==='build'?<AgentBuilder section={id}/>:<NotFound/>}</main><footer><span>בינה איכותנית <span className="footer-separator">/</span> HIGH AI <span className="footer-separator">/</span> ספטמבר 2026</span><span>המקור קודם לתוצר. ההחלטה נשארת אצל החוקר.</span></footer></div></>;}
